# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Simvue Nightlies (Python Versions)

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_suite:
    name: Test Suite
    uses: ./.github/workflows/common.yml
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    with:
      platform: ubuntu-latest
      python-version: ${{ matrix.python-version }}
    secrets: inherit
