# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Simvue Python API (Ubuntu)

on:
  push:
    branches: ["main", "dev", "hotfix/update-ci"]
  pull_request:
    branches: ["main", "dev", "hotfix/update-ci"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_suite:
    name: Test Suite
    uses: ./.github/workflows/common.yml
    with:
      platform: ubuntu-latest
      python-version: "3.14"
    secrets: inherit
