name: Simvue Nightlies (macOS)

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

jobs:
  test_suite:
    name: Test Suite
    uses: ./.github/workflows/common.yml
    with:
      platform: macos-latest
      python-version: "3.14"
    secrets: inherit
